spring:
  datasource:
    url: postgresql://postgres:SLMvCFnLUsvdgrnTfkvGQJLSyWSsGvgQ@postgres-ryv2.railway.internal:5432/railway
    username: postgres
    password: SLMvCFnLUsvdgrnTfkvGQJLSyWSsGvgQ
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  ssl:
    enabled: true
    trust-store: classpath:truststore.jks
    trust-store-password: changeit
