spring:
  profiles:
    active: dev  # Change to prod/test as needed
  jpa:
    hibernate:
      ddl-auto: update  # Auto-create/update tables
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
